server:
  port: 5454

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/service6db
    username: root
    password: 19november2000
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: SIXTH-SERVICE